services:

  sample-app:
    build: ./sample-app
    ports:
      - "3001:3001"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:2.9.4
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  jaeger:
    image: jaegertracing/all-in-one:1.55
    ports:
      - "16686:16686"
      - "14268:14268"

  pyroscope:
    image: grafana/pyroscope:latest
    ports:
      - "4040:4040"

  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "3010:3000"
    depends_on:
      - prometheus
      - loki
      - jaeger

  alloy:
    image: grafana/alloy:latest
    volumes:
      - ./configs/alloy/config.alloy:/etc/alloy/config.alloy