version: "3.8"

services:

  sample-app:
    build: ./sample-app
    ports:
      - "3001:3001"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:latest
    volumes:
      - ./configs/loki/loki-config.yml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  tempo:
    image: grafana/tempo:latest
    volumes:
      - ./configs/tempo/tempo.yml:/etc/tempo/tempo.yml
    command: -config.file=/etc/tempo/tempo.yml
    ports:
      - "3200:3200"

  pyroscope:
    image: grafana/pyroscope
    ports:
      - "4040:4040"

  grafana:
    image: grafana/grafana
    volumes:
      - ./configs/grafana:/etc/grafana/provisioning
    ports:
      - "3000:3000"

  alloy:
    image: grafana/alloy
    volumes:
      - ./configs/alloy/config.alloy:/etc/alloy/config.alloy